INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_FTXXXREAD FTxxxRead)

FIND_PATH(
    FTXXXREAD_INCLUDE_DIRS
    NAMES FTxxxRead/api.h
    HINTS $ENV{FTXXXREAD_DIR}/include
        ${PC_FTXXXREAD_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    FTXXXREAD_LIBRARIES
    NAMES gnuradio-FTxxxRead
    HINTS $ENV{FTXXXREAD_DIR}/lib
        ${PC_FTXXXREAD_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FTXXXREAD DEFAULT_MSG FTXXXREAD_LIBRARIES FTXXXREAD_INCLUDE_DIRS)
MARK_AS_ADVANCED(FTXXXREAD_LIBRARIES FTXXXREAD_INCLUDE_DIRS)

